name: livekit_components
description: "Out-of-the-box flutter widgets for livekit client."
version: 1.1.1
homepage: https://github.com/livekit/components-flutter

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  chat_bubbles: ^1.6.0
  flutter:
    sdk: flutter
  flutter_background: ^1.3.0+1
  flutter_webrtc: ^0.12.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  livekit_client: ^2.3.6
  provider: ^6.1.2
  responsive_builder: ^0.7.1
  collection: ^1.18.0
  equatable: ^2.0.5
  file_picker: ^8.1.4
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0


topics:
  - webrtc
  - ai
  - livestream
  - conference
  - agent

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
